# Generated by Django 5.0.7 on 2024-08-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waitlists", "0003_waitlistentry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
